### ISSUE TITLE
Can't read anything

### ISSUE THREAD

**Issue by zlefler** [learn-co-curriculum/phase-3-lecture-videos-sql-select#3]
### Canvas Link

https://learning.flatironschool.com/courses/4980/pages/video-sql-select?module_item_id=366626

### Concern

Y'all, this is completely illegible. Maybe you could redo it zoomed in? But as it is, it might as well just be an audio recording.

### Suggested Changes

https://www.businessinsider.com/how-to-zoom-in-on-pc

https://support.apple.com/en-us/HT210978

**Comment by lizbur10** [comment]
Hi @Leavingvalhalla ! Thanks for bringing this to our attention. The problem has been documented and will be addressed when the video is updated, so I'm going to go ahead and close this issue.

Thanks for contributing to the Flatiron School curriculum! 💙
